// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/class/add": {
            "post": {
                "description": "添加新班级",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "班级管理"
                ],
                "summary": "添加班级",
                "parameters": [
                    {
                        "description": "班级信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateClassDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/class/list": {
            "get": {
                "description": "分页获取班级列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "班级管理"
                ],
                "summary": "获取班级列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量(默认20)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/class/{id}": {
            "put": {
                "description": "编辑现有班级",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "班级管理"
                ],
                "summary": "编辑班级",
                "parameters": [
                    {
                        "description": "班级信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateClassDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "编辑成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除现有班级",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "班级管理"
                ],
                "summary": "删除班级",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "班级ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "description": "用户登录系统",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.LoginUserDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "认证失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/user/register": {
            "post": {
                "description": "注册新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateUserDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "响应数据"
                },
                "message": {
                    "description": "响应信息",
                    "type": "string"
                }
            }
        },
        "service.CreateClassDTO": {
            "type": "object",
            "required": [
                "name",
                "teacher_id"
            ],
            "properties": {
                "description": {
                    "description": "班级描述",
                    "type": "string"
                },
                "name": {
                    "description": "班级名称",
                    "type": "string"
                },
                "teacher_id": {
                    "description": "教师ID",
                    "type": "integer"
                }
            }
        },
        "service.CreateUserDTO": {
            "type": "object",
            "required": [
                "name",
                "password",
                "student_id"
            ],
            "properties": {
                "name": {
                    "description": "用户名",
                    "type": "string",
                    "minLength": 2
                },
                "password": {
                    "description": "密码",
                    "type": "string",
                    "minLength": 6
                },
                "student_id": {
                    "description": "学号",
                    "type": "string",
                    "minLength": 5
                }
            }
        },
        "service.LoginUserDTO": {
            "type": "object",
            "required": [
                "password",
                "student_id"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "student_id": {
                    "description": "学号",
                    "type": "string"
                }
            }
        },
        "service.UpdateClassDTO": {
            "type": "object",
            "required": [
                "code",
                "id",
                "name",
                "teacher_id"
            ],
            "properties": {
                "code": {
                    "description": "班级代码",
                    "type": "string"
                },
                "description": {
                    "description": "班级描述",
                    "type": "string"
                },
                "id": {
                    "description": "班级ID",
                    "type": "integer"
                },
                "name": {
                    "description": "班级名称",
                    "type": "string"
                },
                "teacher_id": {
                    "description": "教师ID",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AI Course API",
	Description:      "AI Course 后端 API 服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
