basePath: /
definitions:
  response.Response:
    properties:
      code:
        description: 业务状态码
        type: integer
      data:
        description: 响应数据
      message:
        description: 响应信息
        type: string
    type: object
  service.CreateClassDTO:
    properties:
      description:
        description: 班级描述
        type: string
      name:
        description: 班级名称
        type: string
      teacher_id:
        description: 教师ID
        type: integer
    required:
    - name
    - teacher_id
    type: object
  service.CreateUserDTO:
    properties:
      name:
        description: 用户名
        minLength: 2
        type: string
      password:
        description: 密码
        minLength: 6
        type: string
      student_id:
        description: 学号
        minLength: 5
        type: string
    required:
    - name
    - password
    - student_id
    type: object
  service.LoginUserDTO:
    properties:
      password:
        description: 密码
        type: string
      student_id:
        description: 学号
        type: string
    required:
    - password
    - student_id
    type: object
  service.UpdateClassDTO:
    properties:
      code:
        description: 班级代码
        type: string
      description:
        description: 班级描述
        type: string
      id:
        description: 班级ID
        type: integer
      name:
        description: 班级名称
        type: string
      teacher_id:
        description: 教师ID
        type: integer
    required:
    - code
    - id
    - name
    - teacher_id
    type: object
info:
  contact: {}
  description: AI Course 后端 API 服务
  title: AI Course API
  version: "1.0"
paths:
  /api/class/{id}:
    delete:
      description: 删除现有班级
      parameters:
      - description: 班级ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: 删除班级
      tags:
      - 班级管理
    put:
      consumes:
      - application/json
      description: 编辑现有班级
      parameters:
      - description: 班级信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.UpdateClassDTO'
      produces:
      - application/json
      responses:
        "200":
          description: 编辑成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: 编辑班级
      tags:
      - 班级管理
  /api/class/add:
    post:
      consumes:
      - application/json
      description: 添加新班级
      parameters:
      - description: 班级信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.CreateClassDTO'
      produces:
      - application/json
      responses:
        "200":
          description: 添加成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: 添加班级
      tags:
      - 班级管理
  /api/class/list:
    get:
      description: 分页获取班级列表
      parameters:
      - description: 页码
        in: query
        name: page
        required: true
        type: integer
      - description: 每页数量(默认20)
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取班级列表
      tags:
      - 班级管理
  /api/user/login:
    post:
      consumes:
      - application/json
      description: 用户登录系统
      parameters:
      - description: 登录信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.LoginUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: 认证失败
          schema:
            $ref: '#/definitions/response.Response'
      summary: 用户登录
      tags:
      - 用户管理
  /api/user/register:
    post:
      consumes:
      - application/json
      description: 注册新用户
      parameters:
      - description: 注册信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.CreateUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: 用户注册
      tags:
      - 用户管理
swagger: "2.0"
